name: Release n8n-nodes-immojump

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Release configuration
          release-type: node
          # Use PAT if GITHUB_TOKEN doesn't have enough permissions
          token: ${{ secrets.APP_TOKEN }}

  build-and-publish:
    needs: release-please
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.release_created

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Verify package structure
        run: |
          echo "Verifying n8n package structure..."
          test -f dist/nodes/Immojump/Immojump.node.js || (echo "❌ Missing main node file" && exit 1)
          test -f dist/credentials/ImmojumpApi.credentials.js || (echo "❌ Missing credentials file" && exit 1)
          echo "✅ Package structure verified"

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: n8n-package-dist-${{ needs.release-please.outputs.version }}
          path: ./dist/
          retention-days: 90

  build-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !needs.release-please.outputs.release_created
    needs: release-please

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Verify package structure
        run: |
          echo "Verifying n8n package structure..."
          test -f dist/nodes/Immojump/Immojump.node.js || (echo "❌ Missing main node file" && exit 1)
          test -f dist/credentials/ImmojumpApi.credentials.js || (echo "❌ Missing credentials file" && exit 1)
          echo "✅ Package structure verified"

